// historical context for each decade
export const historicalContext = {
  1760: "The Stamp Act of 1765 imposed a direct tax on the colonies by the British government, requiring many printed materials in the colonies to be produced on stamped paper produced in London, carrying an embossed revenue stamp.",
  1780: "During the Revolutionary War, the beginnings of the new U.S. postal system relied on manual postmarks with the location and date to facilitate communication among the colonies as they moved away from British-issued stamps.",
  1800: "The Postal Service Act of 1792 created a formal U.S. Post Office. Experimentation with standardized markings (precursors to embossed seals) reflected the shift toward a national postal identity, independent of Britain.",
  1840: "The 1847 was the U.S.’s first official stamp release, anchoring Revolutionary leaders like George Washington and Benjamin Franklin as symbols of national legitimacy.",
  1850: "This decade reflects the popularization of adhesive stamps as postage became standardized and accessible nationwide. At the same time, the growing number of stamps featuring national leaders mirrors the rising sectional tensions before the Civil War, as imagery of unity and founding ideals was used to reinforce national identity amid political division.",
  1860: "During the Civil War, both the Union and Confederate states issued their own postage stamps. Union issues celebrated Washington, Franklin, and patriotic symbols like the eagle, while Confederate issues showed Davis and state leaders.",
  1870: "Departmental stamps for Treasury, War, Navy, Agriculture, etc. symbolized Reconstruction and the expansion of federal authority. “Liberty” and “Justice” begin appearing explicitly, echoing post-war ideals of unity and equality.",
  1880: "An increase in allegorical figures, classical muses, and themes of discovery, anticipating the grand Columbian Exposition of 1893. These designs reveal how the U.S. was using stamps to myth-make national identity, linking classical ideals with narratives of progress and discovery",
  1890: "The landmark 1893 Columbian Exposition Issue commemorated the 400th anniversary of Columbus’s voyage, with a sprawling set of stamps illustrating discovery, conquest, and nationhood. The popularity of these stamps reflected a Gilded Age America eager to project itself as both modern and rooted in heroic origins.",
}